version: '3'
services:
  minio-storage:
    image: minio/minio
    container_name: minio-storage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: changeme
    volumes:
      - ./storage/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - minio-network

  minio-app:
    container_name: minio-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      MINIO_HOST: ${MINIO_HOST:-minio-storage}
      MINIO_PORT: ${MINIO_PORT:-9000}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-access_key}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-secret_key}
    networks:
      - minio-network
      
networks:
  minio-network:
    driver: 'bridge'